import type { Metadata } from "next";
import Script from 'next/script'

import { Inter } from "next/font/google";
import "./globals.css";
import GridLayout from "@/components/GridLayout";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "House Cafe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  // readonly children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <head>
        {/* <Script src="http://localhost:8097"></Script> */}
      </head>
      <body className={inter.className}>
        <GridLayout>
     
          {children}
        </GridLayout>
      </body>

    </html>
  );
}
